:toc: macro
:toc-title:
:toclevels: 99

# Dot files

toc::[]

## Introduction

Some configuration files that I like to use.

### bash aliases
* Debian, place aliases in ~/.bash_aliases, a file loaded by ~/.bashrc.

* Mac, place aliases in ~/.bash_profile.

### vim configuration
In Vim, run :version for a list of configuration files. + 

Mac + 
You should use the ~/.vimrc. There is a global vim configuration file in /usr/share/vim/virc, but files in /usr/share will be overridden by a system upgrade.

Debian + 
To load the vim configuration file by all users, you could also decide to use the global /etc/vim/vimrc.local (not /etc/vim/vimrc), in case you don't want to edit a default file. On most distroes /usr/share/vim/vimrc sources vimrc.local.

### postgresql password file
From the documentation, https://www.postgresql.org/docs/current/libpq-pgpass.html +

* The program must be using the C client library libpq to connect to PostgreSQL (the JDBC driver, for example, doesn't use libpq). +
* The .pgpass file must be in the home directory of the user that owns the process which uses libpq to connect to PostgreSQL. +
* You can override the default location by either putting the variable PGPASSFILE in the process' environment or (from v10 on) with the connection parameter passfile. +
* The .pgpass file must have permissions 0600 or less. +

### ssh config file
Should live in ~/.ssh/config. A convenience file for using ssh. +

### git config file
The global git config files is openened by "git config --global --edit", it lives in ~/.gitconfig on all platforms. `man git config` for a comprehensive overview of git configuration properties.





